name: Project board management

on:
  schedule:
    # Everyday at 18:09 (randomly chosen)
    - cron: '09 18 * * *'
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PROD: 1
          REPO: NixOS/nixpkgs
          TEAM: NixOS/security-review
          ORG: NixOS
          PROJECT_NUMBER: 111
        run: |
          tmp=$(mktemp -d)
          trap 'rm -rf "$tmp"' exit

          log() {
            echo >&2 "$@"
          }

          effect() {
            if [[ -z "${PROD:-}" ]]; then
              log "Skipping in non-prod mode:" "${@@Q}"
            else
              "$@"
            fi
          }

          searchIssues() {
            log "Querying $*"
            if ! >"$tmp/out" gh api --method GET search/issues \
              --paginate -f per_page=100 \
              -f q="repo:$REPO $*" \
              --jq '.items[] | "\(.id) \(.number)"'; then
              log "Failed: $(<"$tmp/out")"
              exit 1
            fi
            cat "$tmp/out"
          }

          addItem() {
            local type=$1
            local id=$2
            if ! res=$(effect gh api --method POST "/orgs/$ORG/projectsV2/$PROJECT_NUMBER/items" -f type="$type" -F id="$id"); then
              if jq -e '.status == 422' <<< "$res"; then
                log "Already added"
              else
                log "Failed: $res"
                exit 1
              fi
            fi
          }

          log "Checking project access"
          if ! res=$(gh api /orgs/"$ORG"/projectsV2/"$PROJECT_NUMBER"); then
            echo "Failed: $res"
            exit 1
          fi

          declare -a issues=()
          while read -r issueId number; do
            issues[issueId]=$number
          done < <({
            log "Fetching all not-yet-added issues where the team was mentioned"
            searchIssues team:"$TEAM" is:issue -project:"$ORG/$PROJECT_NUMBER"
          })
          log "Adding not-yet-added issues where the team was mentioned"
          declare -p issues
          for issueId in "${!issues[@]}"; do
            log "+ Adding $issueId (https://github.com/$REPO/issue/${issues[$issueId]})"
            addItem Issue "$issueId"
          done

          log "Fetching PRs which have been updated since last review"
          pull_request_query='
          query($org: String!, $projectNumber: Int!, $endCursor: String) {
            organization(login: $org) {
              projectV2(number: $projectNumber) {
                id
                field(name: "Status") {
                  ... on ProjectV2SingleSelectField {
                    id
                    options {
                      name
                      id
                    }
                  }
                }
                items(first: 100, after: $endCursor, query: "is:pr") {
                  pageInfo {
                    hasNextPage
                    endCursor
                  }
                  nodes {
                    id
                    updatedAt
                    fieldValueByName(name: "Status") {
                      ... on ProjectV2ItemFieldSingleSelectValue {
                        name
                      }
                    }
                    content {
                      ... on PullRequest {
                        url
                        timelineItems(itemTypes: [PULL_REQUEST_COMMIT, HEAD_REF_FORCE_PUSHED_EVENT], last: 1) {
                          updatedAt
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          '
          if ! >"$tmp/prs.json" gh api graphql --paginate -F "query=$pull_request_query" -F org="$ORG" -F projectNumber="$PROJECT_NUMBER"; then
            log "Failed: $(<"$tmp/prs.json")"
            exit 1
          fi

          update_field_mutation='
          mutation ($projectId: ID!, $itemId: ID!, $fieldId: ID!, $selectId: String!) {
            updateProjectV2ItemFieldValue(
              input: {
                projectId: $projectId
                fieldId: $fieldId
                itemId: $itemId
                value: { singleSelectOptionId: $selectId }
              }
            ) {
              projectV2Item {
                id
              }
            }
          }
          '

          project_id="$(jq -r ".data.organization.projectV2.id" "$tmp/prs.json")"
          field_id="$(jq -r ".data.organization.projectV2.field.id" "$tmp/prs.json")"
          select_id="$(jq -r ".data.organization.projectV2.field.options | .[] | select(.name == \"Needs Re-review\") | .id" "$tmp/prs.json")"

          while read item_id pr_url; do
            log "~ Moving PR $pr_url to \"Needs Re-review\""
            if ! >"$tmp/out" gh api graphql -F "query=$update_field_mutation" -F "projectId=$project_id" -F "itemId=$item_id" -F "fieldId=$field_id" -F "selectId=$select_id"; then
              echo "Failed: $(<"$tmp/out")"
              exit 1
            fi
          done < <(
            jq -r '.data.organization.projectV2.items.nodes
              | .[]
              | select(.fieldValueByName.name == "Reviewed" and .updatedAt <= .content.timelineItems.updatedAt)
              | (.id + " " + .content.url)' \
             "$tmp/prs.json"
          )

          log "Fetching all not-yet-added PRs"
          declare -a prs=()
          while read -r _issueId number; do
            log "* Fetching PR id for https://github.com/$REPO/pull/$number"
            prId="$(gh api "/repos/$REPO/pulls/$number" --jq .id)"
            prs[prId]=$number
          done < <({
            log "Fetching all PRs where the team was mentioned"
            searchIssues team:"$TEAM" is:pr -project:$ORG/$PROJECT_NUMBER
            log "Fetching all PRs where the team was requested for review"
            searchIssues team-review-requested:"$TEAM" is:pr -project:$ORG/$PROJECT_NUMBER
          })

          log "Adding not-yet-added PRs where the team was mentioned or requested for review"
          declare -p prs
          for prId in "${!prs[@]}"; do
            log "+ Adding PR https://github.com/$REPO/pull/${prs[prId]}"
            addItem PullRequest "$prId"
          done
