name: Project board management

on:
  schedule:
    # Everyday at 18:09 (randomly chosen)
    - cron: '09 18 * * *'
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PROD: 1
          REPO: NixOS/nixpkgs
          TEAM: NixOS/security-review
          ORG: NixOS
          PROJECT_NUMBER: 111
        run: |
          tmp=$(mktemp -d)
          trap 'rm -rf "$tmp"' exit

          log() {
            echo >&2 "$@"
          }

          effect() {
            if [[ -z "${PROD:-}" ]]; then
              log "Skipping in non-prod mode:" "${@@Q}"
            else
              "$@"
            fi
          }

          searchIssues() {
            log "Querying $*"
            if ! >"$tmp/out" gh api --method GET search/issues \
              --paginate -f per_page=100 \
              -f q="repo:$REPO $*" \
              --jq '.items[] | "\(.id) \(.number)"'; then
              log "Failed: $(<"$tmp/out")"
              exit 1
            fi
            cat "$tmp/out"
          }

          addItem() {
            local type=$1
            local id=$2
            if ! res=$(effect gh api --method POST "/orgs/$ORG/projectsV2/$PROJECT_NUMBER/items" -f type="$type" -F id="$id"); then
              if jq -e '.status == 422' <<< "$res"; then
                log "Already added"
              else
                log "Failed: $res"
                exit 1
              fi
            fi
          }

          log "Checking project access"
          if ! res=$(gh api /orgs/"$ORG"/projectsV2/"$PROJECT_NUMBER"); then
            echo "Failed: $res"
            exit 1
          fi

          declare -a issues=()
          while read -r issueId number; do
            issues[issueId]=$number
          done < <({
            log "Fetching all not-yet-added issues where the team was mentioned"
            searchIssues team:"$TEAM" is:issue -project:"$ORG/$PROJECT_NUMBER"
          })
          log "Adding not-yet-added issues where the team was mentioned"
          declare -p issues
          for issueId in "${!issues[@]}"; do
            log "Adding $issueId (https://github.com/$REPO/issue/${issues[$issueId]})"
            addItem Issue "$issueId"
          done


          log "Fetching all PRs already added to the project"
          if ! >"$tmp/out" gh api --paginate "/orgs/$ORG/projectsV2/$PROJECT_NUMBER/items" \
            --jq ".[] | select(.content_type == \"PullRequest\" and .content.base.repo.full_name == \"$REPO\") .content.number"; then
            log "Failed: $(<"$tmp/out")"
            exit 1
          fi
          declare -a items=()
          while read -r number; do
            items[number]=
          done < "$tmp/out"
          log "Got ${#items[@]} project items"

          log "Fetching PRs and filtering for ones not yet added to the project"
          declare -a prs=()
          while read -r _issueId number; do
            # Only add items we don't already have
            if [[ ! -v items[number] ]]; then
              log "Fetching PR id for https://github.com/$REPO/pull/$number"
              prId="$(gh api "/repos/$REPO/pulls/$number" --jq .id)"
              prs[prId]=$number
            fi
          done < <({
            log "Fetching all PRs where the team was mentioned"
            searchIssues team:"$TEAM" is:pr
            log "Fetching all PRs where the team was requested for review"
            searchIssues team-review-requested:"$TEAM" is:pr
          })

          log "Adding not-yet-added PRs where the team was mentioned or requested for review"
          declare -p prs
          for prId in "${!prs[@]}"; do
            log "Adding $prId (https://github.com/$REPO/pull/${prs[prId]})"
            addItem PullRequest "$prId"
          done
